<?php

namespace ContainerOQtrymU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJeuxControllerajouterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bi5wJBR.App\Controller\JeuxController::ajouter()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bi5wJBR.App\\Controller\\JeuxController::ajouter()'] = ($container->privates['.service_locator.bi5wJBR'] ?? $container->load('get_ServiceLocator_Bi5wJBRService'))->withContext('App\\Controller\\JeuxController::ajouter()', $container);
    }
}
