<?php

namespace ContainerOQtrymU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStagesControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hI60JPL.App\Controller\StagesController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hI60JPL.App\\Controller\\StagesController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'stage' => ['privates', '.errored..service_locator.hI60JPL.App\\Entity\\Stage', NULL, 'Cannot autowire service ".service_locator.hI60JPL": it needs an instance of "App\\Entity\\Stage" but this type has been excluded in "config/services.yaml".'],
        ], [
            'stage' => 'App\\Entity\\Stage',
        ]))->withContext('App\\Controller\\StagesController::show()', $container);
    }
}
