<?php

namespace ContainerCh646s9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VWsKtKRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vWsKtKR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vWsKtKR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'stage' => ['privates', '.errored..service_locator.vWsKtKR.App\\Entity\\Stage', NULL, 'Cannot autowire service ".service_locator.vWsKtKR": it needs an instance of "App\\Entity\\Stage" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'stage' => 'App\\Entity\\Stage',
            'entityManager' => '?',
        ]);
    }
}
