<?php

namespace ContainerCh646s9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatTournoisControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Wv1IiEv.App\Controller\CatTournoisController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Wv1IiEv.App\\Controller\\CatTournoisController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\CatTournoisRepository', 'getCatTournoisRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\CatTournoisRepository',
        ]))->withContext('App\\Controller\\CatTournoisController::index()', $container);
    }
}
