<?php

namespace ContainerCh646s9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJeuxControllersupprimerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JPI8Ytd.App\Controller\JeuxController::supprimer()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JPI8Ytd.App\\Controller\\JeuxController::supprimer()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'jeux' => ['privates', '.errored..service_locator.JPI8Ytd.App\\Entity\\JeuVideo', NULL, 'Cannot autowire service ".service_locator.JPI8Ytd": it needs an instance of "App\\Entity\\JeuVideo" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'jeux' => 'App\\Entity\\JeuVideo',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\JeuxController::supprimer()', $container);
    }
}
