<?php

namespace ContainerCh646s9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStagesControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jDaX71Q.App\Controller\StagesController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jDaX71Q.App\\Controller\\StagesController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'stageRepository' => ['privates', 'App\\Repository\\StageRepository', 'getStageRepositoryService', true],
        ], [
            'stageRepository' => 'App\\Repository\\StageRepository',
        ]))->withContext('App\\Controller\\StagesController::index()', $container);
    }
}
