<?php

namespace ContainerCh646s9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStage2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vWsKtKR.App\Entity\Stage' shared service.
     *
     * @return \App\Entity\Stage
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.vWsKtKR": it needs an instance of "App\\Entity\\Stage" but this type has been excluded in "config/services.yaml".');
    }
}
